#include <doctest/doctest.h>
#include <lexer/lex.hpp>

TEST_SUITE_BEGIN("lexer");

TEST_CASE("queens.tig")
{
  lexer::Scanner scanner(std::filesystem::path("../tests/queens.tig"));

  const lexer::Token tokens[] = {
    {lexer::TokenType::let_keyword, "let", 2},

    {lexer::TokenType::var_keyword, "var", 3},
    {lexer::TokenType::identifier, "N", 3},
    {lexer::TokenType::assign_op, ":=", 3},
    {lexer::TokenType::integer_literal, "8", 3},

    {lexer::TokenType::type_keyword, "type", 4},
    {lexer::TokenType::identifier, "intArray", 4},
    {lexer::TokenType::equal_op, "=", 4},
    {lexer::TokenType::array_keyword, "array", 4},
    {lexer::TokenType::of_keyword, "of", 4},
    {lexer::TokenType::identifier, "int", 4},

    {lexer::TokenType::var_keyword, "var", 6},
    {lexer::TokenType::identifier, "row", 6},
    {lexer::TokenType::assign_op, ":=", 6},
    {lexer::TokenType::identifier, "intArray", 6},
    {lexer::TokenType::lbracket, "[", 6},
    {lexer::TokenType::identifier, "N", 6},
    {lexer::TokenType::rbracket, "]", 6},
    {lexer::TokenType::of_keyword, "of", 6},
    {lexer::TokenType::integer_literal, "0", 6},

    {lexer::TokenType::var_keyword, "var", 7},
    {lexer::TokenType::identifier, "col", 7},
    {lexer::TokenType::assign_op, ":=", 7},
    {lexer::TokenType::identifier, "intArray", 7},
    {lexer::TokenType::lbracket, "[", 7},
    {lexer::TokenType::identifier, "N", 7},
    {lexer::TokenType::rbracket, "]", 7},
    {lexer::TokenType::of_keyword, "of", 7},
    {lexer::TokenType::integer_literal, "0", 7},

    {lexer::TokenType::var_keyword, "var", 8},
    {lexer::TokenType::identifier, "diagl", 8},
    {lexer::TokenType::assign_op, ":=", 8},
    {lexer::TokenType::identifier, "intArray", 8},
    {lexer::TokenType::lbracket, "[", 8},
    {lexer::TokenType::identifier, "N", 8},
    {lexer::TokenType::plus_op, "+", 8},
    {lexer::TokenType::identifier, "N", 8},
    {lexer::TokenType::minus_op, "-", 8},
    {lexer::TokenType::integer_literal, "1", 8},
    {lexer::TokenType::rbracket, "]", 8},
    {lexer::TokenType::of_keyword, "of", 8},
    {lexer::TokenType::integer_literal, "0", 8},

    {lexer::TokenType::var_keyword, "var", 9},
    {lexer::TokenType::identifier, "diag2", 9},
    {lexer::TokenType::assign_op, ":=", 9},
    {lexer::TokenType::identifier, "intArray", 9},
    {lexer::TokenType::lbracket, "[", 9},
    {lexer::TokenType::identifier, "N", 9},
    {lexer::TokenType::plus_op, "+", 9},
    {lexer::TokenType::identifier, "N", 9},
    {lexer::TokenType::minus_op, "-", 9},
    {lexer::TokenType::integer_literal, "1", 9},
    {lexer::TokenType::rbracket, "]", 9},
    {lexer::TokenType::of_keyword, "of", 9},
    {lexer::TokenType::integer_literal, "0", 9},

    {lexer::TokenType::function_keyword, "function", 11},
    {lexer::TokenType::identifier, "printboard", 11},
    {lexer::TokenType::lparen, "(", 11},
    {lexer::TokenType::rparen, ")", 11},
    {lexer::TokenType::equal_op, "=", 11},

    {lexer::TokenType::lparen, "(", 12},
    {lexer::TokenType::for_keyword, "for", 12},
    {lexer::TokenType::identifier, "i", 12},
    {lexer::TokenType::assign_op, ":=", 12},
    {lexer::TokenType::integer_literal, "0", 12},
    {lexer::TokenType::to_keyword, "to", 12},
    {lexer::TokenType::identifier, "N", 12},
    {lexer::TokenType::minus_op, "-", 12},
    {lexer::TokenType::integer_literal, "1", 12},

    {lexer::TokenType::do_keyword, "do", 13},
    {lexer::TokenType::lparen, "(", 13},
    {lexer::TokenType::for_keyword, "for", 13},
    {lexer::TokenType::identifier, "j", 13},
    {lexer::TokenType::assign_op, ":=", 13},
    {lexer::TokenType::integer_literal, "0", 13},
    {lexer::TokenType::to_keyword, "to", 13},
    {lexer::TokenType::identifier, "N", 13},
    {lexer::TokenType::minus_op, "-", 13},
    {lexer::TokenType::integer_literal, "1", 13},

    {lexer::TokenType::do_keyword, "do", 14},
    {lexer::TokenType::identifier, "print", 14},
    {lexer::TokenType::lparen, "(", 14},
    {lexer::TokenType::if_keyword, "if", 14},
    {lexer::TokenType::identifier, "col", 14},
    {lexer::TokenType::lbracket, "[", 14},
    {lexer::TokenType::identifier, "i", 14},
    {lexer::TokenType::rbracket, "]", 14},
    {lexer::TokenType::equal_op, "=", 14},
    {lexer::TokenType::identifier, "j", 14},
    {lexer::TokenType::then_keyword, "then", 14},
    {lexer::TokenType::string_literal, " O", 14},
    {lexer::TokenType::else_keyword, "else", 14},
    {lexer::TokenType::string_literal, " . ", 14},
    {lexer::TokenType::rparen, ")", 14},
    {lexer::TokenType::semicolon, ";", 14},

    {lexer::TokenType::identifier, "print", 15},
    {lexer::TokenType::lparen, "(", 15},
    {lexer::TokenType::string_literal, "\n", 15},
    {lexer::TokenType::rparen, ")", 15},
    {lexer::TokenType::rparen, ")", 15},
    {lexer::TokenType::semicolon, ";", 15},

    {lexer::TokenType::identifier, "print", 16},
    {lexer::TokenType::lparen, "(", 16},
    {lexer::TokenType::string_literal, "\n", 16},
    {lexer::TokenType::rparen, ")", 16},
    {lexer::TokenType::rparen, ")", 16},

    {lexer::TokenType::function_keyword, "function", 18},
    {lexer::TokenType::identifier, "try", 18},
    {lexer::TokenType::lparen, "(", 18},
    {lexer::TokenType::identifier, "c", 18},
    {lexer::TokenType::colon, ":", 18},
    {lexer::TokenType::identifier, "int", 18},
    {lexer::TokenType::rparen, ")", 18},
    {lexer::TokenType::equal_op, "=", 18},

    {lexer::TokenType::if_keyword, "if", 19},
    {lexer::TokenType::identifier, "c", 19},
    {lexer::TokenType::equal_op, "=", 19},
    {lexer::TokenType::identifier, "N", 19},

    {lexer::TokenType::then_keyword, "then", 20},
    {lexer::TokenType::identifier, "printboard", 20},
    {lexer::TokenType::lparen, "(", 20},
    {lexer::TokenType::rparen, ")", 20},

    {lexer::TokenType::else_keyword, "else", 21},
    {lexer::TokenType::for_keyword, "for", 21},
    {lexer::TokenType::identifier, "r", 21},
    {lexer::TokenType::assign_op, ":=", 21},
    {lexer::TokenType::integer_literal, "0", 21},
    {lexer::TokenType::to_keyword, "to", 21},
    {lexer::TokenType::identifier, "N", 21},
    {lexer::TokenType::minus_op, "-", 21},
    {lexer::TokenType::integer_literal, "1", 21},

    {lexer::TokenType::do_keyword, "do", 22},
    {lexer::TokenType::if_keyword, "if", 22},
    {lexer::TokenType::identifier, "row", 22},
    {lexer::TokenType::lbracket, "[", 22},
    {lexer::TokenType::identifier, "r", 22},
    {lexer::TokenType::rbracket, "]", 22},
    {lexer::TokenType::equal_op, "=", 22},
    {lexer::TokenType::integer_literal, "0", 22},
    {lexer::TokenType::and_op, "&", 22},
    {lexer::TokenType::identifier, "diagl", 22},
    {lexer::TokenType::lbracket, "[", 22},
    {lexer::TokenType::identifier, "r", 22},
    {lexer::TokenType::plus_op, "+", 22},
    {lexer::TokenType::identifier, "c", 22},
    {lexer::TokenType::rbracket, "]", 22},
    {lexer::TokenType::equal_op, "=", 22},
    {lexer::TokenType::integer_literal, "0", 22},
    {lexer::TokenType::and_op, "&", 22},
    {lexer::TokenType::identifier, "diag2", 22},
    {lexer::TokenType::lbracket, "[", 22},
    {lexer::TokenType::identifier, "r", 22},
    {lexer::TokenType::plus_op, "+", 22},
    {lexer::TokenType::integer_literal, "7", 22},
    {lexer::TokenType::minus_op, "-", 22},
    {lexer::TokenType::identifier, "c", 22},
    {lexer::TokenType::rbracket, "]", 22},
    {lexer::TokenType::equal_op, "=", 22},
    {lexer::TokenType::integer_literal, "0", 22},

    {lexer::TokenType::then_keyword, "then", 23},
    {lexer::TokenType::lparen, "(", 23},
    {lexer::TokenType::identifier, "row", 23},
    {lexer::TokenType::lbracket, "[", 23},
    {lexer::TokenType::identifier, "r", 23},
    {lexer::TokenType::rbracket, "]", 23},
    {lexer::TokenType::assign_op, ":=", 23},
    {lexer::TokenType::integer_literal, "1", 23},
    {lexer::TokenType::semicolon, ";", 23},
    {lexer::TokenType::identifier, "diagl", 23},
    {lexer::TokenType::lbracket, "[", 23},
    {lexer::TokenType::identifier, "r", 23},
    {lexer::TokenType::plus_op, "+", 23},
    {lexer::TokenType::identifier, "c", 23},
    {lexer::TokenType::rbracket, "]", 23},
    {lexer::TokenType::assign_op, ":=", 23},
    {lexer::TokenType::integer_literal, "1", 23},
    {lexer::TokenType::semicolon, ";", 23},
    {lexer::TokenType::identifier, "diag2", 23},
    {lexer::TokenType::lbracket, "[", 23},
    {lexer::TokenType::identifier, "r", 23},
    {lexer::TokenType::plus_op, "+", 23},
    {lexer::TokenType::integer_literal, "7", 23},
    {lexer::TokenType::minus_op, "-", 23},
    {lexer::TokenType::identifier, "c", 23},
    {lexer::TokenType::rbracket, "]", 23},
    {lexer::TokenType::assign_op, ":=", 23},
    {lexer::TokenType::integer_literal, "1", 23},
    {lexer::TokenType::semicolon, ";", 23},

    {lexer::TokenType::identifier, "col", 24},
    {lexer::TokenType::lbracket, "[", 24},
    {lexer::TokenType::identifier, "c", 24},
    {lexer::TokenType::rbracket, "]", 24},
    {lexer::TokenType::assign_op, ":=", 24},
    {lexer::TokenType::identifier, "r", 24},
    {lexer::TokenType::semicolon, ";", 24},

    {lexer::TokenType::identifier, "try", 25},
    {lexer::TokenType::lparen, "(", 25},
    {lexer::TokenType::identifier, "c", 25},
    {lexer::TokenType::plus_op, "+", 25},
    {lexer::TokenType::integer_literal, "1", 25},
    {lexer::TokenType::rparen, ")", 25},
    {lexer::TokenType::semicolon, ";", 25},

    {lexer::TokenType::identifier, "row", 26},
    {lexer::TokenType::lbracket, "[", 26},
    {lexer::TokenType::identifier, "r", 26},
    {lexer::TokenType::rbracket, "]", 26},
    {lexer::TokenType::assign_op, ":=", 26},
    {lexer::TokenType::integer_literal, "0", 26},
    {lexer::TokenType::semicolon, ";", 26},
    {lexer::TokenType::identifier, "diagl", 26},
    {lexer::TokenType::lbracket, "[", 26},
    {lexer::TokenType::identifier, "r", 26},
    {lexer::TokenType::plus_op, "+", 26},
    {lexer::TokenType::identifier, "c", 26},
    {lexer::TokenType::rbracket, "]", 26},
    {lexer::TokenType::assign_op, ":=", 26},
    {lexer::TokenType::integer_literal, "0", 26},
    {lexer::TokenType::semicolon, ";", 26},
    {lexer::TokenType::identifier, "diag2", 26},
    {lexer::TokenType::lbracket, "[", 26},
    {lexer::TokenType::identifier, "r", 26},
    {lexer::TokenType::plus_op, "+", 26},
    {lexer::TokenType::integer_literal, "7", 26},
    {lexer::TokenType::minus_op, "-", 26},
    {lexer::TokenType::identifier, "c", 26},
    {lexer::TokenType::rbracket, "]", 26},
    {lexer::TokenType::assign_op, ":=", 26},
    {lexer::TokenType::integer_literal, "0", 26},
    {lexer::TokenType::rparen, ")", 26},

    {lexer::TokenType::in_keyword, "in", 27},
    {lexer::TokenType::identifier, "try", 27},
    {lexer::TokenType::lparen, "(", 27},
    {lexer::TokenType::integer_literal, "0", 27},
    {lexer::TokenType::rparen, ")", 27},

    {lexer::TokenType::end_keyword, "end", 28}};

  for(auto t : tokens) {
    CHECK(scanner.next() == t);
  }

  CHECK(scanner.next().type == lexer::TokenType::eof);
}

TEST_CASE("merge.tig")
{
  lexer::Scanner scanner(std::filesystem::path("../tests/merge.tig"));

  const lexer::Token tokens[] = {
    {lexer::TokenType::let_keyword, "let", 1},

    {lexer::TokenType::type_keyword, "type", 2},
    {lexer::TokenType::identifier, "any", 2},
    {lexer::TokenType::equal_op, "=", 2},
    {lexer::TokenType::lbrace, "{", 2},
    {lexer::TokenType::identifier, "any", 2},
    {lexer::TokenType::colon, ":", 2},
    {lexer::TokenType::identifier, "int", 2},
    {lexer::TokenType::rbrace, "}", 2},

    {lexer::TokenType::var_keyword, "var", 3},
    {lexer::TokenType::identifier, "buffer", 3},
    {lexer::TokenType::assign_op, ":=", 3},
    {lexer::TokenType::identifier, "getchar", 3},
    {lexer::TokenType::lparen, "(", 3},
    {lexer::TokenType::rparen, ")", 3},

    {lexer::TokenType::function_keyword, "function", 4},
    {lexer::TokenType::identifier, "readint", 4},
    {lexer::TokenType::lparen, "(", 4},
    {lexer::TokenType::identifier, "any", 4},
    {lexer::TokenType::colon, ":", 4},
    {lexer::TokenType::identifier, "any", 4},
    {lexer::TokenType::rparen, ")", 4},
    {lexer::TokenType::colon, ":", 4},
    {lexer::TokenType::identifier, "int", 4},
    {lexer::TokenType::equal_op, "=", 4},

    {lexer::TokenType::let_keyword, "let", 5},
    {lexer::TokenType::var_keyword, "var", 5},
    {lexer::TokenType::identifier, "i", 5},
    {lexer::TokenType::assign_op, ":=", 5},
    {lexer::TokenType::integer_literal, "0", 5},

    {lexer::TokenType::function_keyword, "function", 6},
    {lexer::TokenType::identifier, "isdigit", 6},
    {lexer::TokenType::lparen, "(", 6},
    {lexer::TokenType::identifier, "s", 6},
    {lexer::TokenType::colon, ":", 6},
    {lexer::TokenType::identifier, "string", 6},
    {lexer::TokenType::rparen, ")", 6},
    {lexer::TokenType::colon, ":", 6},
    {lexer::TokenType::identifier, "int", 6},
    {lexer::TokenType::equal_op, "=", 6},

    {lexer::TokenType::identifier, "ord", 7},
    {lexer::TokenType::lparen, "(", 7},
    {lexer::TokenType::identifier, "buffer", 7},
    {lexer::TokenType::rparen, ")", 7},
    {lexer::TokenType::greater_equal_op, ">=", 7},
    {lexer::TokenType::identifier, "ord", 7},
    {lexer::TokenType::lparen, "(", 7},
    {lexer::TokenType::string_literal, "0", 7},
    {lexer::TokenType::rparen, ")", 7},
    {lexer::TokenType::and_op, "&", 7},
    {lexer::TokenType::identifier, "ord", 7},
    {lexer::TokenType::lparen, "(", 7},
    {lexer::TokenType::identifier, "buffer", 7},
    {lexer::TokenType::rparen, ")", 7},
    {lexer::TokenType::less_equal_op, "<=", 7},
    {lexer::TokenType::identifier, "ord", 7},
    {lexer::TokenType::lparen, "(", 7},
    {lexer::TokenType::string_literal, "9", 7},
    {lexer::TokenType::rparen, ")", 7},

    {lexer::TokenType::in_keyword, "in", 8},
    {lexer::TokenType::while_keyword, "while", 8},
    {lexer::TokenType::identifier, "buffer", 8},
    {lexer::TokenType::equal_op, "=", 8},
    {lexer::TokenType::string_literal, " ", 8},
    {lexer::TokenType::or_op, "|", 8},
    {lexer::TokenType::identifier, "buffer", 8},
    {lexer::TokenType::equal_op, "=", 8},
    {lexer::TokenType::string_literal, "\n", 8},
    {lexer::TokenType::do_keyword, "do", 8},
    {lexer::TokenType::identifier, "buffer", 8},
    {lexer::TokenType::assign_op, ":=", 8},
    {lexer::TokenType::identifier, "getchar", 8},
    {lexer::TokenType::lparen, "(", 8},
    {lexer::TokenType::rparen, ")", 8},

    {lexer::TokenType::identifier, "any", 9},
    {lexer::TokenType::dot_op, ".", 9},
    {lexer::TokenType::identifier, "any", 9},
    {lexer::TokenType::assign_op, ":=", 9},
    {lexer::TokenType::identifier, "isdigit", 9},
    {lexer::TokenType::lparen, "(", 9},
    {lexer::TokenType::identifier, "buffer", 9},
    {lexer::TokenType::rparen, ")", 9},
    {lexer::TokenType::semicolon, ";", 9},

    {lexer::TokenType::while_keyword, "while", 10},
    {lexer::TokenType::identifier, "isdigit", 10},
    {lexer::TokenType::lparen, "(", 10},
    {lexer::TokenType::identifier, "buffer", 10},
    {lexer::TokenType::rparen, ")", 10},

    {lexer::TokenType::do_keyword, "do", 11},
    {lexer::TokenType::lparen, "(", 11},
    {lexer::TokenType::identifier, "i", 11},
    {lexer::TokenType::assign_op, ":=", 11},
    {lexer::TokenType::identifier, "i", 11},
    {lexer::TokenType::times_op, "*", 11},
    {lexer::TokenType::integer_literal, "10", 11},
    {lexer::TokenType::plus_op, "+", 11},
    {lexer::TokenType::identifier, "ord", 11},
    {lexer::TokenType::lparen, "(", 11},
    {lexer::TokenType::identifier, "buffer", 11},
    {lexer::TokenType::rparen, ")", 11},
    {lexer::TokenType::minus_op, "-", 11},
    {lexer::TokenType::identifier, "ord", 11},
    {lexer::TokenType::lparen, "(", 11},
    {lexer::TokenType::string_literal, "0", 11},
    {lexer::TokenType::rparen, ")", 11},
    {lexer::TokenType::semicolon, ";", 11},

    {lexer::TokenType::identifier, "buffer", 12},
    {lexer::TokenType::assign_op, ":=", 12},
    {lexer::TokenType::identifier, "getchar", 12},
    {lexer::TokenType::lparen, "(", 12},
    {lexer::TokenType::rparen, ")", 12},
    {lexer::TokenType::rparen, ")", 12},
    {lexer::TokenType::semicolon, ";", 12},

    {lexer::TokenType::identifier, "i", 13},

    {lexer::TokenType::end_keyword, "end", 14},

    {lexer::TokenType::type_keyword, "type", 16},
    {lexer::TokenType::identifier, "list", 16},
    {lexer::TokenType::equal_op, "=", 16},
    {lexer::TokenType::lbrace, "{", 16},
    {lexer::TokenType::identifier, "first", 16},
    {lexer::TokenType::colon, ":", 16},
    {lexer::TokenType::identifier, "int", 16},
    {lexer::TokenType::comma, ",", 16},
    {lexer::TokenType::identifier, "rest", 16},
    {lexer::TokenType::colon, ":", 16},
    {lexer::TokenType::identifier, "list", 16},
    {lexer::TokenType::rbrace, "}", 16},

    {lexer::TokenType::function_keyword, "function", 18},
    {lexer::TokenType::identifier, "readlist", 18},
    {lexer::TokenType::lparen, "(", 18},
    {lexer::TokenType::rparen, ")", 18},
    {lexer::TokenType::colon, ":", 18},
    {lexer::TokenType::identifier, "list", 18},
    {lexer::TokenType::equal_op, "=", 18},

    {lexer::TokenType::let_keyword, "let", 19},
    {lexer::TokenType::var_keyword, "var", 19},
    {lexer::TokenType::identifier, "any", 19},
    {lexer::TokenType::assign_op, ":=", 19},
    {lexer::TokenType::identifier, "any", 19},
    {lexer::TokenType::lbrace, "{", 19},
    {lexer::TokenType::identifier, "any", 19},
    {lexer::TokenType::equal_op, "=", 19},
    {lexer::TokenType::integer_literal, "0", 19},
    {lexer::TokenType::rbrace, "}", 19},

    {lexer::TokenType::var_keyword, "var", 20},
    {lexer::TokenType::identifier, "i", 20},
    {lexer::TokenType::assign_op, ":=", 20},
    {lexer::TokenType::identifier, "readint", 20},
    {lexer::TokenType::lparen, "(", 20},
    {lexer::TokenType::identifier, "any", 20},
    {lexer::TokenType::rparen, ")", 20},

    {lexer::TokenType::in_keyword, "in", 21},
    {lexer::TokenType::if_keyword, "if", 21},
    {lexer::TokenType::identifier, "any", 21},
    {lexer::TokenType::dot_op, ".", 21},
    {lexer::TokenType::identifier, "any", 21},

    {lexer::TokenType::then_keyword, "then", 22},
    {lexer::TokenType::identifier, "list", 22},
    {lexer::TokenType::lbrace, "{", 22},
    {lexer::TokenType::identifier, "first", 22},
    {lexer::TokenType::equal_op, "=", 22},
    {lexer::TokenType::identifier, "i", 22},
    {lexer::TokenType::comma, ",", 22},
    {lexer::TokenType::identifier, "rest", 22},
    {lexer::TokenType::equal_op, "=", 22},
    {lexer::TokenType::identifier, "readlist", 22},
    {lexer::TokenType::lparen, "(", 22},
    {lexer::TokenType::rparen, ")", 22},
    {lexer::TokenType::rbrace, "}", 22},

    {lexer::TokenType::else_keyword, "else", 23},
    {lexer::TokenType::lparen, "(", 23},
    {lexer::TokenType::identifier, "buffer", 23},
    {lexer::TokenType::assign_op, ":=", 23},
    {lexer::TokenType::identifier, "getchar", 23},
    {lexer::TokenType::lparen, "(", 23},
    {lexer::TokenType::rparen, ")", 23},
    {lexer::TokenType::semicolon, ";", 23},
    {lexer::TokenType::nil_keyword, "nil", 23},
    {lexer::TokenType::rparen, ")", 23},

    {lexer::TokenType::end_keyword, "end", 24},

    {lexer::TokenType::function_keyword, "function", 27},
    {lexer::TokenType::identifier, "merge", 27},
    {lexer::TokenType::lparen, "(", 27},
    {lexer::TokenType::identifier, "a", 27},
    {lexer::TokenType::colon, ":", 27},
    {lexer::TokenType::identifier, "list", 27},
    {lexer::TokenType::comma, ",", 27},
    {lexer::TokenType::identifier, "b", 27},
    {lexer::TokenType::colon, ":", 27},
    {lexer::TokenType::identifier, "list", 27},
    {lexer::TokenType::rparen, ")", 27},
    {lexer::TokenType::colon, ":", 27},
    {lexer::TokenType::identifier, "list", 27},
    {lexer::TokenType::equal_op, "=", 27},

    {lexer::TokenType::if_keyword, "if", 28},
    {lexer::TokenType::identifier, "a", 28},
    {lexer::TokenType::equal_op, "=", 28},
    {lexer::TokenType::nil_keyword, "nil", 28},
    {lexer::TokenType::then_keyword, "then", 28},
    {lexer::TokenType::identifier, "b", 28},

    {lexer::TokenType::else_keyword, "else", 29},
    {lexer::TokenType::if_keyword, "if", 29},
    {lexer::TokenType::identifier, "b", 29},
    {lexer::TokenType::equal_op, "=", 29},
    {lexer::TokenType::nil_keyword, "nil", 29},
    {lexer::TokenType::then_keyword, "then", 29},
    {lexer::TokenType::identifier, "a", 29},

    {lexer::TokenType::else_keyword, "else", 30},
    {lexer::TokenType::if_keyword, "if", 30},
    {lexer::TokenType::identifier, "a", 30},
    {lexer::TokenType::dot_op, ".", 30},
    {lexer::TokenType::identifier, "first", 30},
    {lexer::TokenType::less_op, "<", 30},
    {lexer::TokenType::identifier, "b", 30},
    {lexer::TokenType::dot_op, ".", 30},
    {lexer::TokenType::identifier, "first", 30},

    {lexer::TokenType::then_keyword, "then", 31},
    {lexer::TokenType::identifier, "list", 31},
    {lexer::TokenType::lbrace, "{", 31},
    {lexer::TokenType::identifier, "first", 31},
    {lexer::TokenType::equal_op, "=", 31},
    {lexer::TokenType::identifier, "a", 31},
    {lexer::TokenType::dot_op, ".", 31},
    {lexer::TokenType::identifier, "first", 31},
    {lexer::TokenType::comma, ",", 31},
    {lexer::TokenType::identifier, "rest", 31},
    {lexer::TokenType::equal_op, "=", 31},
    {lexer::TokenType::identifier, "merge", 31},
    {lexer::TokenType::lparen, "(", 31},
    {lexer::TokenType::identifier, "a", 31},
    {lexer::TokenType::dot_op, ".", 31},
    {lexer::TokenType::identifier, "rest", 31},
    {lexer::TokenType::comma, ",", 31},
    {lexer::TokenType::identifier, "b", 31},
    {lexer::TokenType::rparen, ")", 31},
    {lexer::TokenType::rbrace, "}", 31},

    {lexer::TokenType::else_keyword, "else", 32},
    {lexer::TokenType::identifier, "list", 32},
    {lexer::TokenType::lbrace, "{", 32},
    {lexer::TokenType::identifier, "first", 32},
    {lexer::TokenType::equal_op, "=", 32},
    {lexer::TokenType::identifier, "b", 32},
    {lexer::TokenType::dot_op, ".", 32},
    {lexer::TokenType::identifier, "first", 32},
    {lexer::TokenType::comma, ",", 32},
    {lexer::TokenType::identifier, "rest", 32},
    {lexer::TokenType::equal_op, "=", 32},
    {lexer::TokenType::identifier, "merge", 32},
    {lexer::TokenType::lparen, "(", 32},
    {lexer::TokenType::identifier, "a", 32},
    {lexer::TokenType::comma, ",", 32},
    {lexer::TokenType::identifier, "b", 32},
    {lexer::TokenType::dot_op, ".", 32},
    {lexer::TokenType::identifier, "rest", 32},
    {lexer::TokenType::rparen, ")", 32},
    {lexer::TokenType::rbrace, "}", 32},

    {lexer::TokenType::function_keyword, "function", 34},
    {lexer::TokenType::identifier, "printint", 34},
    {lexer::TokenType::lparen, "(", 34},
    {lexer::TokenType::identifier, "i", 34},
    {lexer::TokenType::colon, ":", 34},
    {lexer::TokenType::identifier, "int", 34},
    {lexer::TokenType::rparen, ")", 34},
    {lexer::TokenType::equal_op, "=", 34},

    {lexer::TokenType::let_keyword, "let", 35},
    {lexer::TokenType::function_keyword, "function", 35},
    {lexer::TokenType::identifier, "f", 35},
    {lexer::TokenType::lparen, "(", 35},
    {lexer::TokenType::identifier, "i", 35},
    {lexer::TokenType::colon, ":", 35},
    {lexer::TokenType::identifier, "int", 35},
    {lexer::TokenType::rparen, ")", 35},
    {lexer::TokenType::equal_op, "=", 35},
    {lexer::TokenType::if_keyword, "if", 35},
    {lexer::TokenType::identifier, "i", 35},
    {lexer::TokenType::greater_op, ">", 35},
    {lexer::TokenType::integer_literal, "0", 35},

    {lexer::TokenType::then_keyword, "then", 36},
    {lexer::TokenType::lparen, "(", 36},
    {lexer::TokenType::identifier, "f", 36},
    {lexer::TokenType::lparen, "(", 36},
    {lexer::TokenType::identifier, "i", 36},
    {lexer::TokenType::divide_op, "/", 36},
    {lexer::TokenType::integer_literal, "10", 36},
    {lexer::TokenType::rparen, ")", 36},
    {lexer::TokenType::semicolon, ";", 36},
    {lexer::TokenType::identifier, "print", 36},
    {lexer::TokenType::lparen, "(", 36},
    {lexer::TokenType::identifier, "chr", 36},
    {lexer::TokenType::lparen, "(", 36},
    {lexer::TokenType::identifier, "i", 36},
    {lexer::TokenType::minus_op, "-", 36},
    {lexer::TokenType::identifier, "i", 36},
    {lexer::TokenType::divide_op, "/", 36},
    {lexer::TokenType::integer_literal, "10", 36},
    {lexer::TokenType::times_op, "*", 36},
    {lexer::TokenType::integer_literal, "10", 36},
    {lexer::TokenType::plus_op, "+", 36},
    {lexer::TokenType::identifier, "ord", 36},
    {lexer::TokenType::lparen, "(", 36},
    {lexer::TokenType::string_literal, "0", 36},
    {lexer::TokenType::rparen, ")", 36},
    {lexer::TokenType::rparen, ")", 36},
    {lexer::TokenType::rparen, ")", 36},
    {lexer::TokenType::rparen, ")", 36},

    {lexer::TokenType::in_keyword, "in", 37},
    {lexer::TokenType::if_keyword, "if", 37},
    {lexer::TokenType::identifier, "i", 37},
    {lexer::TokenType::less_op, "<", 37},
    {lexer::TokenType::integer_literal, "0", 37},
    {lexer::TokenType::then_keyword, "then", 37},
    {lexer::TokenType::lparen, "(", 37},
    {lexer::TokenType::identifier, "print", 37},
    {lexer::TokenType::lparen, "(", 37},
    {lexer::TokenType::string_literal, "-", 37},
    {lexer::TokenType::rparen, ")", 37},
    {lexer::TokenType::semicolon, ";", 37},
    {lexer::TokenType::identifier, "f", 37},
    {lexer::TokenType::lparen, "(", 37},
    {lexer::TokenType::minus_op, "-", 37},
    {lexer::TokenType::identifier, "i", 37},
    {lexer::TokenType::rparen, ")", 37},
    {lexer::TokenType::rparen, ")", 37},

    {lexer::TokenType::else_keyword, "else", 38},
    {lexer::TokenType::if_keyword, "if", 38},
    {lexer::TokenType::identifier, "i", 38},
    {lexer::TokenType::greater_op, ">", 38},
    {lexer::TokenType::integer_literal, "0", 38},
    {lexer::TokenType::then_keyword, "then", 38},
    {lexer::TokenType::identifier, "f", 38},
    {lexer::TokenType::lparen, "(", 38},
    {lexer::TokenType::identifier, "i", 38},
    {lexer::TokenType::rparen, ")", 38},

    {lexer::TokenType::else_keyword, "else", 39},
    {lexer::TokenType::identifier, "print", 39},
    {lexer::TokenType::lparen, "(", 39},
    {lexer::TokenType::string_literal, "0", 39},
    {lexer::TokenType::rparen, ")", 39},

    {lexer::TokenType::end_keyword, "end", 40},

    {lexer::TokenType::function_keyword, "function", 42},
    {lexer::TokenType::identifier, "printlist", 42},
    {lexer::TokenType::lparen, "(", 42},
    {lexer::TokenType::identifier, "l", 42},
    {lexer::TokenType::colon, ":", 42},
    {lexer::TokenType::identifier, "list", 42},
    {lexer::TokenType::rparen, ")", 42},
    {lexer::TokenType::equal_op, "=", 42},
    {lexer::TokenType::if_keyword, "if", 43},
    {lexer::TokenType::identifier, "l", 43},
    {lexer::TokenType::equal_op, "=", 43},
    {lexer::TokenType::nil_keyword, "nil", 43},
    {lexer::TokenType::then_keyword, "then", 43},
    {lexer::TokenType::identifier, "print", 43},
    {lexer::TokenType::lparen, "(", 43},
    {lexer::TokenType::string_literal, "\n", 43},
    {lexer::TokenType::rparen, ")", 43},
    {lexer::TokenType::else_keyword, "else", 44},
    {lexer::TokenType::lparen, "(", 44},
    {lexer::TokenType::identifier, "printint", 44},
    {lexer::TokenType::lparen, "(", 44},
    {lexer::TokenType::identifier, "l", 44},
    {lexer::TokenType::dot_op, ".", 44},
    {lexer::TokenType::identifier, "first", 44},
    {lexer::TokenType::rparen, ")", 44},
    {lexer::TokenType::semicolon, ";", 44},
    {lexer::TokenType::identifier, "print", 44},
    {lexer::TokenType::lparen, "(", 44},
    {lexer::TokenType::string_literal, " ", 44},
    {lexer::TokenType::rparen, ")", 44},
    {lexer::TokenType::semicolon, ";", 44},
    {lexer::TokenType::identifier, "printlist", 44},
    {lexer::TokenType::lparen, "(", 44},
    {lexer::TokenType::identifier, "l", 44},
    {lexer::TokenType::dot_op, ".", 44},
    {lexer::TokenType::identifier, "rest", 44},
    {lexer::TokenType::rparen, ")", 44},
    {lexer::TokenType::rparen, ")", 44},

    {lexer::TokenType::in_keyword, "in", 47},
    {lexer::TokenType::identifier, "printlist", 47},
    {lexer::TokenType::lparen, "(", 47},
    {lexer::TokenType::identifier, "merge", 47},
    {lexer::TokenType::lparen, "(", 47},
    {lexer::TokenType::identifier, "readlist", 47},
    {lexer::TokenType::lparen, "(", 47},
    {lexer::TokenType::rparen, ")", 47},
    {lexer::TokenType::comma, ",", 47},
    {lexer::TokenType::identifier, "readlist", 47},
    {lexer::TokenType::lparen, "(", 47},
    {lexer::TokenType::rparen, ")", 47},
    {lexer::TokenType::rparen, ")", 47},
    {lexer::TokenType::rparen, ")", 47},

    {lexer::TokenType::end_keyword, "end", 48},

  };

  for(auto t : tokens) {
    CHECK(scanner.next() == t);
  }

  CHECK(scanner.next().type == lexer::TokenType::eof);
}

TEST_SUITE_END();